apiVersion: v1
kind: Secret
metadata:
  name: prestashop-secret
type: Opaque
data:
   PRESTASHOP_DATABASE_PORT_NUMBER: MzMwNg== #3306
   PRESTASHOP_DATABASE_USER: Ym5fcHJlc3Rhc2hvcA== #bn_prestashop
   PRESTASHOP_DATABASE_PASSWORD: Yml0bmFtaQ== #bitnami
   PRESTASHOP_DATABASE_NAME: Yml0bmFtaV9wcmVzdGFzaG9w #bitnami_prestashop
